//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "application")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub icon_id: String,
    pub description: Option<String>,
    pub homepage_url: String,
    pub creator_id: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub redirect_uris: String,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub grant_types: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::application_access_grant::Entity")]
    ApplicationAccessGrant,
    #[sea_orm(has_many = "super::application_secret::Entity")]
    ApplicationSecret,
    #[sea_orm(has_many = "super::authorization_code::Entity")]
    AuthorizationCode,
    #[sea_orm(
        belongs_to = "super::image::Entity",
        from = "Column::IconId",
        to = "super::image::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Image,
    #[sea_orm(has_many = "super::token::Entity")]
    Token,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatorId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::application_access_grant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApplicationAccessGrant.def()
    }
}

impl Related<super::application_secret::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApplicationSecret.def()
    }
}

impl Related<super::authorization_code::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthorizationCode.def()
    }
}

impl Related<super::image::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Image.def()
    }
}

impl Related<super::token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Token.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
